blog2/miniblog/miniblog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('user_login/',views.user_login,name='login'),
    path('user_logout/',views.user_logout,name='logout'),
    path('addpost/',views.add_post,name='addpost'),
    path('updatepost/<int:id>/',views.update_post,
    name='updatepost'),
    path('delete/<int:id>/',views.delete_post,
    name='deletepost'),

]

blog2/miniblog/blog/models.py
from django.db import models

# Create your models here.

class blogpost(models.Model):

    title=models.CharField(max_length=150)
    desc=models.TextField()
    

blog2/miniblog/blog/forms.py
from cProfile import label
from dataclasses import field
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext, gettext_lazy as _
from .models import blogpost
# from miniblog.blog.models import blogpost


class SignupForm(UserCreationForm):

    password1 = forms.CharField(
        label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password(again)',
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:

        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        labels = {'first_name': 'First Name',
                  'last_name': 'Last Name', 'email': 'Email'}
        widgets = {

            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),

        }


class LoginForm(AuthenticationForm):

    username = UsernameField(widget=forms.TextInput(
        attrs={'autofocus': True, 'class': 'form-control'}))
    password = forms.CharField(label=_("Password"), strip=False, widget=forms.PasswordInput(
        attrs={'autocomplete': 'current_password', 'class': 'form-control'}))


class blogpostform(forms.ModelForm):

    class Meta:

        model = blogpost
        fields = ['title', 'desc']
        labels = {'title': 'Title', 'desc': 'Description'}
        widgets = {'title': forms.TextInput(attrs={
            'class': 'form-control'}),
            'desc': forms.Textarea(attrs={
                'class': 'form-control'}), }

blog2/miniblog/blog/views.py
from django.shortcuts import render
from email.headerregistry import Group
from django import forms
from django.shortcuts import render,HttpResponseRedirect
from .forms import LoginForm,blogpostform
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from .models import blogpost
from django.contrib.auth.models import Group


def home(request):

    posts=blogpost.objects.all()
    return render(request,'blog/home.html',{'posts':posts})


def about(request):

    return render(request,'blog/about.html')


def contact(request):

    return render(request,'blog/contact.html')


def dashboard(request):

 if request.user.is_authenticated:
  posts=blogpost.objects.all()
  user=request.user
  full_name=user.get_full_name()
  gps=user.groups.all()
  return render(request,'blog/dashboard.html',{'posts':posts,'full_name':full_name,'groups':gps})
 else:
  return HttpResponseRedirect('/user_login/')

def user_logout(request):

    logout(request)
    return HttpResponseRedirect('/')




def user_login(request):

   if not request.user.is_authenticated:
    if request.method=="POST":
     form=LoginForm(request=request,data=request.POST)
     if form.is_valid():
       uname=form.cleaned_data['username']
       upass=form.cleaned_data['password']
       user=authenticate(username=uname,password=upass)
       if user is not None:
        login(request,user)
        messages.success(request,'Logged in Successfully !!!')
        return HttpResponseRedirect('/dashboard/')
    else:
     form=LoginForm()
    return render(request,'blog/login.html',{'form':form})  
    
   else:
    return HttpResponseRedirect('/dashboard/')



def add_post(request):

 if request.user.is_authenticated:
  if request.method=='POST':
   form=blogpostform(request.POST)
   if form.is_valid():
    title=form.cleaned_data['title']
    desc=form.cleaned_data['desc']
    pst=blogpost(title=title,desc=desc)
    pst.save()
    messages.success(request,'You have added the post')
    form=blogpostform()
  else:
   form=blogpostform()
  return render(request,'blog/addpost.html',{'form':form}) 
 else:
  return HttpResponseRedirect('/login/')

def update_post(request,id):
 
 if request.user.is_authenticated:
   if request.method=='POST':
     pi=blogpost.objects.get(pk=id)
     form=blogpostform(request.POST,instance=pi)
     if form.is_valid():
       form.save()
       messages.success(request,'You have Updated the post')
   else:
     pi=blogpost.objects.get(pk=id)
     form=blogpostform(instance=pi)

   return render(request,'blog/updatepost.html',{'form':form}) 
 else:
   return HttpResponseRedirect('/login/')

def delete_post(request,id):
 if request.user.is_authenticated:
   if request.method=='POST':
     pi=blogpost.objects.get(pk=id)
     pi.delete()

     return HttpResponseRedirect('/dashboard')
 else:
   return HttpResponseRedirect('/login/')

blog2/miniblog/blog/templates/blog/about.html
{% extends 'blog/base.html' %} {% load static %} {% block content %}

<div class="col-sm-10">
  <h3 class="text-white my-5">About page</h3>

  <p>
    This is a blog system build by Rajvardhan Ramdas Patil.Here I can post the content and user can read the posts.
  </p>
</div>

{% endblock content %}

blog2/miniblog/blog/templates/blog/addpost.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-5">Dashboard/ Add Post</h3>
    
    {% if messages %}
    {% for message in messages %}
    <p  {% if message.tags %} class="alert alert-{{message.tags}} mb-5"  {% endif %}>{{message}}</p>
    {% endfor %}
    {% endif %}
    
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Add" class="btn btn-success">
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
    </form>
</div>

{% endblock content %}

blog2/miniblog/blog/templates/blog/base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    

    
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static '/blog/css/style.css' %}" />

    <title>My Blog</title>
  </head>
  <body>
    <div class="container-fluid bg-dark">
      {% include 'blog/navbar.html' %}
    </div>

    <div class="container">
      <div class="row">
        <div class="col-sm-12">
            {% block msg %} 
            {% endblock msg %}
        </div>
      </div>

      <div class="row">
        {% block side %} 
        {% endblock side %} 

        {% block content %} 
        {% endblock content %}
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
  </body>
</html>

blog2/miniblog/blog/templates/blog/contact.html
{% extends 'blog/base.html' %} 
{% load static %} 
{% block content %}

<div class="col-sm-10">
  <h3 class="text-white my-5">Contact page</h3>
  <form>
    <div class="form-group row">

      <div class="form-group col-md-6">
        <label for="inputName">Name</label>
        <input type="text" class="form-control" id="inputName" />
      </div>

      <div class="form-group col-md-6">
        <label for="inputEmail">Email</label>
        <input type="text" class="form-control" id="inputEmail" />
      </div>

    </div>

    <div class="form-group">
      <label for="inputAddress">Address</label>
      <input type="text" class="form-control" id="inputAddress" />
    </div>

    <div class="form-group">
      <label for="message">Message</label>
      <textarea type="text"
        class="form-control"
        id="message"
        rows="3"
        style="background-color: silver"
      ></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

{% endblock content %}

blog2/miniblog/blog/templates/blog/dashboard.html
{% extends 'blog/base.html' %} 
{% load static %}

{% block msg %}
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show"
  {% endif %}>
  <strong>{{message}}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}
{% endblock msg %}

{% block side %}
<div class="col-sm-2 text-white my-5 text-center">
  <h4 class="my-5">Profile</h4>
  <h5>{{full_name}}</h5>
  {% for group in groups %}
  <p>{{group.name}}</p>
  {% endfor %}
</div>

{% endblock side %}

{% block content %}
<div class="col-sm-10">
  <h3 class="text-white my-5">Dashboard page</h3>
  <a href="{% url 'addpost' %}" class="btn btn-success">Add Post</a>
  
  <h4 class="text-center alert alert-info mt-3">Show Post Information</h4>
  {% if posts %}
  <table class="table table-hover bg-white">
  <thead>
    <tr class="text-center">
      <th scope="col" style="width:2%;color: black;">ID</th>
      <th scope="col" style="width:28%;color: black;">Title</th>
      <th scope="col" style="width:45%;color: black;">Description</th>
      <th scope="col" style="width:15%;color: black;">Action</th>
    </tr>
  </thead >
  
  <tbody>
    {% for blogpost in posts %}
    <tr>
      <th scope="row" style="color: black;">{{blogpost.id}}</th>
      <td style="color: black;">{{blogpost.title}}</td>
      <td style="color: black;">{{blogpost.desc}}</td>
      <td class="text-center">
       <a href="{% url 'updatepost' blogpost.id %}" 
       class="btn btn-warning btn-sm">Edit</a>
       {% if perms.blog.delete_blogpost %}
       <form action="{% url 'deletepost' blogpost.id %}" method="post" class="d-inline">
       {% csrf_token %}
       <input type="submit" class="btn btn-danger btn-sm" value="Delete">
       
      </form>
      {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}

<h4 class="text-center alert alert-warning">No Records</h4>
{% endif %}
</div>
{% endblock content %}

blog2/miniblog/blog/templates/blog/home.html
{% extends 'blog/base.html' %} 
{% load static %}
{% block content %}

<div class="col-sm-10">
  <h3 class="text-white my-5">Home page</h3>

  {% for blogpost in posts %}
  <div class="jumbotron jumbotron-fluid jumbo-color">
    <div class="container">
      <h1 class="display-4 fw-bold">{{blogpost.title}}</h1>
      <p class="lead">{{blogpost.desc}}</p>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}

blog2/miniblog/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}


<div class="col-sm-10">
  <h3 class="text-white my-5">Login page</h3>


    <form action="" method="post" novalidate >
  
      {% csrf_token %}
  
      {% for fm in form %}
  
      <div class="form-group" style="margin-bottom: 15px; ">
      {{fm.label_tag}} {{fm}} <small>{{fm.errors|striptags}}
      </small></div>
  
      {% endfor %}
      <input type="submit" value="Login" class="btn btn-primary">
  
      {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
  
      <p class="alert alert-danger my-3">{{error}}</p>
  
      {% endfor %}
      {% endif %}
  
    </form>
  
</div>

{% endblock content %}

blog2/miniblog/blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">My Blog</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home<span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
      </li>

      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
      {% else %}
       
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav> 

blog2/miniblog/blog/templates/blog/updatepost.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-5">Dashboard/ Update Post</h3>

    {% if messages %}
    {% for message in messages %}
    <p  {% if message.tags %} class="alert alert-{{message.tags}} mb-5"  {% endif %}>{{message}}</p>
    {% endfor %}
    {% endif %}

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update" class="btn btn-success">
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Go To Dashboard</a>
    </form>
</div>

{% endblock content %}